module_admin_controllers:
    resource: ../../src/Module/Admin/Controller/
    type: annotation

module_storefront_controllers:
    resource: ../../src/Module/Storefront/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation
