module_admin_controllers:
    resource: ../src/Modules/Admin/Controller/
    type: annotation

module_storefront_controllers:
    resource: ../src/Modules/Storefront/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

live_component:
    resource: '@LiveComponentBundle/Resources/config/routing/live_component.xml'
    # prefix: '/{_locale}'